---
title: "Homework 2"
author: "Megan Marziali"
output: github_document
---

This document contains my solutions to homework 2 for p8105.

```{r setup}
library(tidyverse)
```

# Problem 1

## Read and clean Mr. Trash Wheel

The following code imports the Mr. Trash Wheel data and cleans the data.

```{r}
trash_wheel = 
  readxl::read_excel("./problem_1/trash_wheel_collection.xlsx", 
                     sheet = "Mr. Trash Wheel",
                     range = "A2:N408",
                     na = "") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls_int = 
           (round(sports_balls) %>% 
           as.integer()))
```

## Read and clean precipiation data

The code below reads in and cleans precipitation data.

```{r}
precip_2017 = 
  readxl::read_excel("./problem_1/trash_wheel_collection.xlsx",
                     sheet = "2017 Precipitation",
                     range = "A2:B14"
                     ) %>% 
  mutate(year = "2017") %>% 
  janitor::clean_names()

precip_2018 = 
  readxl::read_excel("./problem_1/trash_wheel_collection.xlsx",
                     sheet = "2018 Precipitation",
                     range = "A2:B14"
                     ) %>% 
  mutate(year = "2018") %>% 
  janitor::clean_names()
```


