Homework 2
================
Megan Marziali

This document contains my solutions to homework 2 for p8105.

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.0     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.1     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.0     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

# Problem 1

## Read and clean Mr. Trash Wheel

The following code imports the Mr. Trash Wheel data and cleans the data.

``` r
trash_wheel = 
  readxl::read_excel("./problem_1/trash_wheel_collection.xlsx", 
                     sheet = "Mr. Trash Wheel",
                     range = "A2:N408",
                     na = "") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls_int = 
           (round(sports_balls) %>% 
           as.integer()))
```

## Read and clean precipiation data

The code below reads in and cleans precipitation data.

``` r
precip_2017 = 
  readxl::read_excel("./problem_1/trash_wheel_collection.xlsx",
                     sheet = "2017 Precipitation",
                     range = "A2:B14"
                     ) %>% 
  mutate(year = "2017")

precip_2018 = 
  readxl::read_excel("./problem_1/trash_wheel_collection.xlsx",
                     sheet = "2018 Precipitation",
                     range = "A2:B14"
                     ) %>% 
  mutate(year = "2018")

sum(precip_2018$Total)
```

    ## [1] 70.33

``` r
median(precip_2018$total)
```

    ## Warning: Unknown or uninitialised column: `total`.

    ## NULL

``` r
round(median(precip_2018$Total), 2)
```

    ## [1] 5.46

``` r
IQR(precip_2018$Total)
```

    ## [1] 3.9925

``` r
sd(precip_2018$Total)
```

    ## [1] 3.131823

Joining data and converting month to a character variable.

``` r
precip_tidy = 
  bind_rows(precip_2018, precip_2017) %>% 
  janitor::clean_names() %>% 
  mutate(month_name = month.name[month]
         ) 
```

Within the Mr. Trash Wheel dataset, there are 344 observations.

Within the precipitation dataset, there are 12 observations from 2017
and 12 from 2018. The total amount of precipitation in 2017 amounted to
32.93 inches, and 70.33 inches in 2018. The mean and median for
precipitation in 2017 was 2.74 (SD: 2.22) and 2.14 (IQR: 2.82),
respectively; with 2018, the mean precipitation was 5.86 (SD: 3.13) and
median precipitation was 2.14 (IQR: 2.82).

# Problem 2
